name: movie_browser
description: "A movie browser using the OMDb Api"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  auto_injector: ^2.1.1
  event_bus: ^2.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true

  